routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::resource('solicitacoes', 'SolicitacoesController');
Route::get('solicitacoes?categoria={categoria}', 'SolicitacoesController@index')->name('solicitacoes.categorias');
Route::resource('categorias', 'CategoriasController');


Route::post('solicitacoes/{id}/responder', 'RespostasController@resposta')->name('resposta.enviar');


Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function solicitacoes(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/CategoriasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoriasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Solicitacoes;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {

        $solicitacoes = Solicitacoes::paginate(50);
        return view('home')->with('solicitacoes', $solicitacoes);
    }
}

app/Http/Controllers/RespostasController.php
<?php

namespace App\Http\Controllers;

use App\Respostas;
use App\Solicitacoes;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class RespostasController extends Controller
{

    public function resposta($id, Request $request){

        $resposta = new Respostas();
        $resposta->user_id = Auth::user()->id;
        $resposta->solicitacoes_id = $id;
        $resposta->mensagem = $request->mensagem;
        $resposta->valor = $request->valor;
        $resposta->save();

        return redirect()->back()->with('success', 'Resposta enviada com sucesso');

    }

}

app/Http/Controllers/SolicitacoesController.php
<?php

namespace App\Http\Controllers;

use App\Solicitacoes;
use Illuminate\Http\Request;

class SolicitacoesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {


            $oportunidades = Solicitacoes::with(['user', 'categorias'])->get();

            return $oportunidades->toJson();


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $solicitacao = Solicitacoes::find($id);

        return view('frontend.solicitacoes.show')->with('solicitacao', $solicitacao);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/frontend/respostas/create.blade.php
@extends('layouts.app')
@section('content')


<div class="alert alert-info">Respondendo a solicitação de {{$solicitacao->user->name}}</div>




<div class="card" style="margin:0px 0px 15px 0px">
    <div class="card-body">
      <h5 class="profile-title">
          <a href="">
            <img src="https://i.picsum.photos/id/65/200/200.jpg" alt="" class="profile-title-img">
            {{$solicitacao->user->name}}
          </a>
          <span class="float-right">{{$solicitacao->created_at->diffForHumans()}}</span>
        </h5>
<hr>
        <p class="card-text">
            {{$solicitacao->descricao}}
        </p>
        @foreach ($solicitacao->categorias as $categoria )
                Categoria: <a href="">{{$categoria->nome}}</a>
            @endforeach

        <div class="float-right">
            <a href="{{route('solicitacoes.show', $solicitacao->id)}}" class="btn btn-sm btn-primary">Ver <i class="fas fa-eye"></i></a>
            <a href="{{route('resposta.responder', $solicitacao->id)}}" class="btn btn-sm btn-info">Responder <i class="fas fa-reply"></i></a>

        </div>
      <div class="clearfix"></div>
    </div>
  </div>



@endsection

resources/views/frontend/solicitacoes/index.blade.php
@extends('layouts.app')
@section('content')


<div class="alert alert-info">
    {{$solicitacoes->count()}}
</div>

@foreach ($solicitacoes as $solicitacao)
<div class="card" style="margin:0px 0px 15px 0px">
    <div class="card-body">
      <h5 class="profile-title">
          <a href="">
            <img src="https://i.picsum.photos/id/65/200/200.jpg" alt="" class="profile-title-img">
            {{$solicitacao->user->name}}
          </a>
          <span class="float-right">{{$solicitacao->created_at->diffForHumans()}}</span>
        </h5>
<hr>
        <p class="card-text">
            {{$solicitacao->descricao}}
        </p>
        @foreach ($solicitacao->categorias as $categoria )
                Categoria: <a href="">{{$categoria->nome}}</a>
            @endforeach

        <div class="float-right">
            <a href="{{route('solicitacoes.show', $solicitacao->id)}}" class="btn btn-sm btn-primary">Ver <i class="fas fa-eye"></i></a>

        </div>
      <div class="clearfix"></div>
    </div>
  </div>


@endforeach


{{$solicitacoes->links()}}


@endsection

resources/views/frontend/solicitacoes/show.blade.php
@extends('layouts.app')
@section('content')



@if ($message = Session::get('success'))

<div class="alert alert-success alert-block">

	<button type="button" class="close" data-dismiss="alert">×</button>

        <strong>{{ $message }}</strong>

</div>

@endif


<div class="card" style="margin:0px 0px 15px 0px">
    <div class="card-body">
      <h5 class="profile-title">
          <a href="">
            <img src="https://i.picsum.photos/id/65/200/200.jpg" alt="" class="profile-title-img">
            {{$solicitacao->user->name}}
          </a>
          <span class="float-right">{{$solicitacao->created_at->diffForHumans()}}</span>
        </h5>
<hr>
        <p class="card-text">
            {{$solicitacao->descricao}}
        </p>
            @foreach ($solicitacao->categorias as $categoria )
                Categoria: <a href="">{{$categoria->nome}}</a>
            @endforeach


        <p class="card-text">
            {{$solicitacao->info}}
        </p>
        <p class="card-text">
            Prazo: {{$solicitacao->prazo}}
        </p>

        <hr>
        <div class="float-right">


            <a class="btn btn-sm btn-primary" data-toggle="modal" data-target="#modal-resposta-{{$solicitacao->id}}">
                Responder <i class="fas fa-reply"></i>
            </a>



        </div>
      <div class="clearfix"></div>
    </div>
  </div>



  <div class="modal fade" id="modal-resposta-{{$solicitacao->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Enviar Resposta</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{route('resposta.enviar',$solicitacao->id)}}" method="POST">
        <div class="modal-body">



            <div class="form-group">
                <label for="mensagem" class="">{{ __('Mensagem') }}</label>
                    <textarea name="mensagem" id="mensagem"  rows="3" class="form-control"></textarea>
                    @error('mensagem')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
            </div>

            <div class="form-group">
                <label for="valor" class="">{{ __('Valor') }}</label>
                <input type="text" name="valor" id="valor" class="form-control">
                    @error('valor')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
            </div>


            @csrf
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
          <button type="submit" class="btn btn-primary">Enviar Resposta</button>
        </div>
    </form>
      </div>
    </div>
  </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('content')


@foreach ($solicitacoes as $solicitacao)
<div class="card" style="margin:0px 0px 15px 0px">
    <div class="card-body">
      <h5 class="profile-title">
          <a href="">
            <img src="https://i.picsum.photos/id/65/200/200.jpg" alt="" class="profile-title-img">
            {{$solicitacao->user->name}}
          </a>
          <span class="float-right">{{$solicitacao->created_at->diffForHumans()}}</span>
        </h5>
<hr>
        <p class="card-text">
            {{$solicitacao->descricao}}
        </p>
            @foreach ($solicitacao->categorias as $categoria )
                Categoria: <a href="">{{$categoria->nome}}</a>
            @endforeach

        <div class="float-right">
            <a href="{{route('solicitacoes.show', $solicitacao->id)}}" class="btn btn-sm btn-primary">Ver <i class="fas fa-eye"></i></a>
            <a href="{{route('solicitacoes.show', $solicitacao->id)}}" class="btn btn-sm btn-info">Responder <i class="fas fa-reply"></i></a>

        </div>
      <div class="clearfix"></div>
    </div>
  </div>


@endforeach


{{$solicitacoes->links()}}



@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <script src="https://kit.fontawesome.com/01e0724242.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        @include('layouts.navigation')
        <main class="">

            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        @yield('content')
                    </div>
                    <div class="col-md-4">
                        <ul class="list-group ">
                            @foreach ($categorias as $categoria )
                        <li class="list-group-item"><a href="{{route('solicitacoes.categorias', $categoria->nome)}}">{{$categoria->nome}}</a></li>
                         @endforeach
                        </ul>

                    </div>
                </div>
            </div>


        </main>
    </div>
</body>
</html>

resources/views/layouts/navigation.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                <a class="nav-link" href="{{route('solicitacoes.index')}}">Solicitacoes</a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>